"""SQLAlchemy declarative base and common mixin classes.

All ORM models should inherit from Base to participate in migrations.
Common fields (id, created_at, updated_at) are provided via mixins.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base for all SQLAlchemy ORM models.

    All models that should be tracked by Alembic must inherit from this class.
    """

    pass


class UUIDPrimaryKeyMixin:
    """Mixin that adds a UUID primary key column.

    Attributes:
        id: UUID primary key generated by the database.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Primary key UUID",
    )


class TimestampMixin:
    """Mixin that adds created_at / updated_at audit timestamp columns.

    Attributes:
        created_at: Timestamp when the record was first inserted.
        updated_at: Timestamp of the most recent update, auto-refreshed.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Record creation timestamp (UTC)",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Record last-update timestamp (UTC)",
    )


class AuditMixin(UUIDPrimaryKeyMixin, TimestampMixin):
    """Convenience mixin combining UUID primary key and timestamps.

    Inherit from this in models that need both id and audit timestamps.
    """

    pass
